### ISSUE TITLE
Improved app UI.

### ISSUE THREAD

**Issue by bhaskarblur** [neeldoshii/TimeTracker#11]
Hi there, i've made improvements to the app UI and now it is working better.
I would like to contribute more to this app.
Let me know your goals and features for this product and i will design and develop them as contributions.

Thanks

**Comment by bhaskarblur** [comment]
@neeldoshii Please review.

**Comment by neeldoshii** [comment]
Hey @bhaskarblur please don't create issue saying your PR. 
Follow this process.

# Description
Please write a brief description of the bug, including what you expect to happen and what is currently happening.

1. Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
2. Step-by-step reproduction instructions
a. Go to '...'
b. Click on '...'
c. Scroll down to '...'

3. Screenshots or screen recording
If possible, please upload a screenshot or screen recording which demonstrates the bug.
