### ISSUE TITLE
[BUG] - Backward Navigation Icon not working

### ISSUE THREAD

**Issue by TharunBalaji2004** [neeldoshii/TimeTracker#6]
Hi there, @neeldoshii I'm interested to contribute for your project onbehalf of #Hacktoberfest2023. I downloaded and tested your app on my local device, I like the overall app design and concept but there are few bugs involved.

I found the backward navbar icon is not working. So I have given a PR solving this issue.

Kindly assign this task to me 😊

**Comment by neeldoshii** [comment]
looks good go for it ;)

**Comment by TharunBalaji2004** [comment]
Kindly review the open PR #7

**Comment by TharunBalaji2004** [comment]
Thanks for the opportunity @neeldoshii ❤️ From next contribution, I will try to specify the issue briefly with attachments
